### ISSUE TITLE
Packages for Wheezy reported to have moved permanently

### ISSUE THREAD

**Issue by jwarnier** [eLvErDe/hwraid#101]
Error message when 'apt-get update' on Wheezy:
`W: Failed to fetch http://hwraid.le-vert.net/debian/dists/wheezy/main/binary-amd64/Packages  301  Moved Permanently [IP: 163.172.69.161 80]
`
When trying to switch to HTTPS:
`W: Failed to fetch https://hwraid.le-vert.net/debian/dists/wheezy/main/binary-amd64/Packages  gnutls_handshake() failed: A TLS fatal alert has been received.
`
I believe it was still working fine a week or two ago.
This makes me think the automatic redirection to HTTPs is broken somehow.

Please help, and thanks for the good work!

**Comment by eLvErDe** [comment]
Hello,

My bad, I enable a force redirect to HTTPS and it was not intended.
Could you confirm it's back to normal ?

Regards, Adam.
