### ISSUE TITLE
megaclisas-statusd megaraid-statusd megaraidsas-statusd

### ISSUE THREAD

**Issue by stalinCCCP415** [eLvErDe/hwraid#114]
Running Debian 10, and installing from the repo, the 3 services above fail to start with the following error:

`megaclisas-statusd[811]: Starting megaclisas-status monitor: megaclisas-statusddaemon: ignoring unsafe /etc/daemon.conf (/etc is group writable) /
megaclisas-statusd[811]: daemon: fatal: refusing to execute unsafe program: /usr/bin/daemon (/ is group writable)`

Is there a quick fix for this? I am just wrote a bash script to run megaclisas-status and email me if something is not optimal in the meantime

**Comment by eLvErDe** [comment]
Your system is broken. /etc permissions are bad, this is not related to megacli but to your broken system.
