### ISSUE TITLE
Debian package versions: stretch beats buster

### ISSUE THREAD

**Issue by wolfgangkarall** [eLvErDe/hwraid#125]
Hi,

minor issue, but as I saw it by accident while upgrading a first installation to bullseye (hurrah for progress on #124 ): the 2 packages we use were still the versions installed on stretch even tho we upgraded to buster some time ago:

```
$ apt-cache policy mega{cli,ctl}
megacli:
  Installed: 8.07.14-2+Debian.stretch.9.9
  Candidate: 8.07.14-2+Debian.stretch.9.9
  Version table:
 *** 8.07.14-2+Debian.stretch.9.9 100
        100 /var/lib/dpkg/status
     8.07.14-2+Debian.buster.10 500
        500 http://hwraid.le-vert.net/debian buster/main amd64 Packages
megactl:
  Installed: 0.4.1+svn20090725.r6-7+Debian.stretch.9.9
  Candidate: 0.4.1+svn20090725.r6-7+Debian.stretch.9.9
  Version table:
 *** 0.4.1+svn20090725.r6-7+Debian.stretch.9.9 100
        100 /var/lib/dpkg/status
     0.4.1+svn20090725.r6-7+Debian.buster.10 500
        500 http://hwraid.le-vert.net/debian buster/main amd64 Packages
```

The stretch packages worked fine on buster all the time, as I said this is a minor issue. :)

I see the bullseye repo has megacli 8.07.14-3+Debian.11.bullseye which trumps all that and uses the release major number before the release name, which should be the way to go I guess.

Anyway, thanks for all the work!

**Comment by eLvErDe** [comment]
Hello,

That's exactly the reason why I changed the naming scheme ;-)
What's the issue actually ?

**Comment by wolfgangkarall** [comment]
Great, since you're aware there's no issue at all. :)

**Comment by eLvErDe** [comment]
Yep, I'll provide updated package with better naming scheme up to stretch and xenial so it will fix itself !
