### ISSUE TITLE
https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key expired

### ISSUE THREAD

**Issue by jwarnier** [eLvErDe/hwraid#127]
I believe that https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key expired today.

**Comment by jwarnier** [comment]
For whatever reason, it seems to still work on Debian Buster, but not on Debian Stretch, nor Jessie.

**Comment by eLvErDe** [comment]
Hello,

I don't think so, could you please share an error message ?

**Comment by pnlarsson** [comment]
wget fails the https - but curl works (debian buster):

`curl https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key | apt-key add -`

**Comment by eLvErDe** [comment]
It's not, I'm using tones of Buster servers.

Please update your systems, you are both probably running obsolete ca-certificates packages that are missing current roots CA used by letsencrypt certificates
