### ISSUE TITLE
Debian bullseye, repository is now missing

### ISSUE THREAD

**Issue by gzcwnk** [eLvErDe/hwraid#143]
Err:5 http://hwraid.le-vert.net/distrib bullseye Release
  404  Not Found [IP: 163.172.69.161 80]
Reading package lists... Done
E: The repository 'http://hwraid.le-vert.net/distrib bullseye Release' does not have a Release file.

**Comment by eppesuig** [comment]
Hello, the repository seems working now. Could you check again?
Please note that the source I am using is slightly different:
```
deb http://hwraid.le-vert.net/debian bullseye main
```

**Comment by gzcwnk** [comment]
Sorry for the late reply, I have been waiting on parts and time.

Great news!  I just installed the 2 packages fine thankyou!!!

Also this is on Debian12 and as of Jan 2024 works OK,

root@bigxeon:~# megacli -LDInfo -L0 -a0


Adapter 0 -- Virtual Drive Information:
Virtual Drive: 0 (Target Id: 0)
Name                :
RAID Level          : Primary-1, Secondary-0, RAID Level Qualifier-0
Size                : 237.968 GB
Sector Size         : 512
Mirror Data         : 237.968 GB
State               : Optimal
Strip Size          : 64 KB
Number Of Drives    : 2
Span Depth          : 1
Default Cache Policy: WriteThrough, ReadAheadNone, Direct, No Write Cache if Bad BBU
Current Cache Policy: WriteThrough, ReadAheadNone, Direct, No Write Cache if Bad BBU
Default Access Policy: Read/Write
Current Access Policy: Read/Write
Disk Cache Policy   : Disk's Default
Encryption Type     : None
Is VD Cached: No



Exit Code: 0x00
root@bigxeon:~# megaclisas-status
-bash: megaclisas-status: command not found
root@bigxeon:~# apt -y install megaclisas-status --allow-unauthenticated
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  daemon
The following NEW packages will be installed:
  daemon megaclisas-status
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 106 kB of archives.
After this operation, 318 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 daemon amd64 0.8-1+b1 [92.2 kB]
Get:2 http://hwraid.le-vert.net/debian bullseye/main amd64 megaclisas-status all 0.18+Debian.11.bullseye [14.2 kB]
Fetched 106 kB in 1s (123 kB/s)
Selecting previously unselected package daemon.
(Reading database ... 169778 files and directories currently installed.)
Preparing to unpack .../daemon_0.8-1+b1_amd64.deb ...
Unpacking daemon (0.8-1+b1) ...
Selecting previously unselected package megaclisas-status.
Preparing to unpack .../megaclisas-status_0.18+Debian.11.bullseye_all.deb ...
Unpacking megaclisas-status (0.18+Debian.11.bullseye) ...
Setting up daemon (0.8-1+b1) ...
Setting up megaclisas-status (0.18+Debian.11.bullseye) ...
Processing triggers for man-db (2.11.2-2) ...
root@bigxeon:~# megaclisas-status
-- Controller information --
-- ID | H/W Model                | RAM    | Temp | BBU    | Firmware
c0    | LSI MegaRAID SAS 9272-8i | 512MB  | 51C  | Absent | FW: 23.2.1-0065

-- Array information --
-- ID | Type   |    Size |  Strpsz | Flags | DskCache |   Status |  OS Path | CacheCade |InProgress
c0u0  | RAID-1 |    238G |   64 KB | RA,WT |  Default |  Optimal | /dev/sda | None      |None

-- Disk information --
-- ID   | Type | Drive Model                                             | Size     | Status          | Speed    | Temp | Slot ID  | LSI ID
c0u0p0  | SSD  | S14VNYAD200058SAMSUNG SSD PM841 2.5" 7mm 256GB DXT03D0Q | 237.9 Gb | Online, Spun Up | 6.0Gb/s  | 31C  | [252:0]  | 13
c0u0p1  | SSD  | S0NUNEAB911373SAMSUNG SSD PM810 2.5" 7mm 256GB AXM08D1Q | 237.9 Gb | Online, Spun Up | 3.0Gb/s  | N/A  | [252:1]  | 18

root@bigxeon:~#

**Comment by eppesuig** [comment]
Good to know. I am not sure about who could close this issue. Maybe you?

**Comment by gzcwnk** [comment]
Thankyou works fine as shown
