### ISSUE TITLE
Repository for Trusty

### ISSUE THREAD

**Issue by DominicBoettger** [eLvErDe/hwraid#18]
Do you plan to release a repository for trusty (14.04)?

Thanks a lot.

**Comment by rdegennaro** [comment]
Based on some other comments about Wheezy vs. Jessie, I just tried installing debian wheezy.  It seemed to work.  

So to /etc/apt/sources.list I added:
```
deb http://hwraid.le-vert.net/debian wheezy main
```

Then I did:
```
sudo apt-get update && sudo apt-get install megactl megacli megaclisas-status
```
I'm still just learning my way around with the commands.  I hope that helps you.

**Comment by eLvErDe** [comment]
Hello,

I created the trusty repository. Can you give a try and close this ticket if it's working properly ?

Thanks, Adam.
