### ISSUE TITLE
Debian Jessie support for megacli

### ISSUE THREAD

**Issue by lanrat** [eLvErDe/hwraid#19]
Since upgrading to Debian 8 (Jessie) megacli and megaclisas-status do not report any information and do not function.
```
lanrat@serv:~$ megaclisas-status 
-- Controller informations --
-- ID | Model

-- Arrays informations --
-- ID | Type | Size | Status | InProgress

-- Disks informations
-- ID | Model | Status
```
```
lanrat@serv:~$ MegaCli -AdpAllInfo -aAll
                                     

Exit Code: 0x00
```

**Comment by lanrat** [comment]
On Debian Wheezy I just had megacli installed and everything worked perfectly. Once upgrading to Debian Jessie I had the above problem, however after installing megactl (in addition to megacli) everything worked again, megacli, megaclisas-status, and even megasasctl!

I'm not sure why but the megactl makes the megacli package work on Debian Jessie. If a Jessie repo is ever created I suggest making megactl a dependency for megacli. I'm currently using the wheezy repo.

**Comment by eLvErDe** [comment]
Hello,

I created a Jessie repo but it was already working just fine with the wheezy one.
Can you give a try an tell me ? I rather think your adapter is NOT supported by megacli....

Regards, Adam.

**Comment by lanrat** [comment]
When my machine was running wheezy megacli worked fine on its own, so I know my controller is supported.

I just changed to the jessie repo and upgraded to the latest version and now megacli works without megactl installed.
