### ISSUE TITLE
Incorrect components in Release file for Ubuntu Precise

### ISSUE THREAD

**Issue by vincentbernat** [eLvErDe/hwraid#20]
Hi!

The release file for Ubuntu Precise says:

```
Architectures: i386 amd64
Components: hwraid
Date: Thu, 22 May 2014 10:22:39 UTC
Label: hwraid.le-vert.net
Origin: hwraid.le-vert.net
Suite: precise
```

The component should be `main`. Some tool (aptly) seem to choke on this.

**Comment by eLvErDe** [comment]
Hey,

I just regenerated all repo files using main. Can you confirm it fixed the issue for you ?

Best regards, Adam.

**Comment by vincentbernat** [comment]
Yes, it works fine now. Thanks!
