### ISSUE TITLE
sas2ircu-status misses a disk

### ISSUE THREAD

**Issue by nschmalenberger** [eLvErDe/hwraid#23]
Immediately after my last disk device, there is a device in the DISPLAY output delimited by "Device is a unknown device". It has all the same serial number and other attributes as a real disk, but it is a backplane (Dell r510).

So when the last append to the list is run, all of those attributes from the last disk have been written over by this "unknown device", not being one of the delimiters for to append previously seen data when it is not the last.

So I just added "Device is a unknown device" to the possible delimiters, the last disk and then the last backplane get put into the list returned by getDiskList() and the backplanes get filtered out anyway by not being mentioned in the array list.

See patch below
--- /usr/sbin/sas2ircu-status   2014-01-26 15:46:10.000000000 +0000
+++ sas2ircu-status     2015-10-03 03:47:48.542352893 +0000
@@ -95,7 +95,7 @@
   slotid=''
   realid=['','']
   for line in res:
-    if re.match('^Device is a Hard disk._$',line) or re.match('^Device is a Enclosure services device._$',line):
-    if re.match('^Device is a Hard disk._$',line) or re.match('^Device is a Enclosure services device._$',line) or re.match('^Device is a unknown device.*$',line):
     if diskid == -1:
       diskid=diskid+1
     else:

**Comment by eLvErDe** [comment]
Hello,

I released an updated package for sas2ircu-status.
Can you confirm it's working properly now ?

Regards, Adam.
