### ISSUE TITLE
Need megaraidsas-status but installing for Debian only delivers megaclisas-statusd

### ISSUE THREAD

**Issue by ovizii** [eLvErDe/hwraid#25]
The reason I am asking is that there is a difference in their output:

root@james:~# megaclisas-status
-- Controller informations --
-- ID | Model
c0 | LSI MegaRAID SAS 9260-4i

-- Arrays informations --
-- ID | Type | Size | Status | InProgress
c0u0 | RAID1 | 1818G | Optimal | None

-- Disks informations
-- ID | Model | Status
c0u0p0 | PN2134P6JLE8SPHGST HUS724020ALA640 MF6OAA70 | Online, Spun Up
c0u0p1 | PN2134P6JLJJETHGST HUS724020ALA640 MF6OAA70 | Online, Spun Up

root@james:~# megasasctl
a0       LSI MegaRAID SAS 9260-4i encl:1 ldrv:1  batt:good
a0d0      1862GiB RAID 1   1x2  optimal
a0e252s0   1863GiB  a0d0  online
a0e252s1   1863GiB  a0d0  online

I am much more interested in the second one as it is using megasasctl but I am unsure how to use this script and where to get a wrapper for it and how to set it to continuously run just like megaclisas-statusd

**Comment by eLvErDe** [comment]
Hello,

Better read the documentation here:

http://hwraid.le-vert.net/wiki/LSIMegaRAIDSAS

Regards, Adam.

**Comment by ovizii** [comment]
hey Adam,

**thanks for the pointer, that is exactly the site I came from. maybe i misunderstood so please correct me:

**Does this not indicate that megasasctl works? 
root@james:~# **megasasctl
a0 LSI MegaRAID SAS 9260-4i encl:1 ldrv:1 **batt:good
a0d0 1862GiB RAID 1 1x2 optimal
a0e252s0 1863GiB a0d0 online
a0e252s1 1863GiB a0d0 online

**That page further says:
>3.1.2. Periodic checks
>You can write your own script around megasasctl to check your adapter status health periodically. >However, I already did this for you. See megaraid-status below.
>
>megaraidsas-status is a wrapper script around megactl with periodics checks.  

**=> but I am not interested in megactl but in megasasctl.

**megaraidsas-status
-- Arrays informations --
-- ID | Type | Size | Status
a0d0 | RAID 1 | 1862GiB | optimal

-- Disks informations
-- ID | Model | Status | Warnings
a0e252s0 | ATA HGST HUS724020AL 1863GiB | online
a0e252s1 | ATA HGST HUS724020AL 1863GiB | online

**There's no battery info but megasasctl delivers battery output.

**Maybe I'm just confused? Would you mind explaining?

**Comment by eLvErDe** [comment]
Hello,

Its actually the same package containing both tools.

Adam.

On November 4, 2015 12:12:50 AM GMT+01:00, ovizii <notifications@github.com> wrote:
>hey Adam,
>
>**thanks for the pointer, that is exactly the site I came from. maybe i
>misunderstood so please correct me:
>
>**Does this not indicate that megasasctl works? 
>root@james:~# **megasasctl
>a0 LSI MegaRAID SAS 9260-4i encl:1 ldrv:1 **batt:good
>a0d0 1862GiB RAID 1 1x2 optimal
>a0e252s0 1863GiB a0d0 online
>a0e252s1 1863GiB a0d0 online
>
>**That page further says:
>>3.1.2. Periodic checks
>>You can write your own script around megasasctl to check your adapter
>status health periodically. >However, I already did this for you. See
>megaraid-status below.
>>
>>megaraidsas-status is a wrapper script around megactl with periodics
>checks.  
>
>**=> but I am not interested in megactl but in megasasctl.
>
>**megaraidsas-status
>-- Arrays informations --
>-- ID | Type | Size | Status
>a0d0 | RAID 1 | 1862GiB | optimal
>
>-- Disks informations
>-- ID | Model | Status | Warnings
>a0e252s0 | ATA HGST HUS724020AL 1863GiB | online
>a0e252s1 | ATA HGST HUS724020AL 1863GiB | online
>
>**There's no battery info but megasasctl delivers battery output.
>
>**Maybe I'm just confused? Would you mind explaining?
>
>
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/eLvErDe/hwraid/issues/25#issuecomment-153518546

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by ovizii** [comment]
**OK, one last question, maybe you can help me figure this out:**

**NONE of these scripts seems to be using megasasctl and that is the only command which shows anything about the battery status:**
>/etc/init.d/megaclisas-statusd   
>/etc/init.d/megaraid-statusd
>/etc/init.d/megaraidsas-statusd

All I'm looking for is for some kind of warning mechanism when there are battery issues. Not sure if its possible anyway.

**Comment by eLvErDe** [comment]
Hello,

Please update your package, today's megaclisas-status update provide battery information.

Regards, Adam.
