### ISSUE TITLE
megaclisas-status fails when arrays aren't consecutive

### ISSUE THREAD

**Issue by jbergler** [eLvErDe/hwraid#26]
We have a controller where array 0 was deleted leaving just array 1 & 2, reporting this for tracking.
PR incoming.

```
sudo megaclisas-status
-- Controller informations --
-- ID | Model
c0 | Cisco 12G SAS Modular Raid Controller

-- Arrays informations --
-- ID | Type | Size | Status | InProgress
Traceback (most recent call last):
  File "/usr/sbin/megaclisas-status", line 166, in <module>
    arrayinfo = returnArrayInfo(output,controllerid,arrayid)
  File "/usr/sbin/megaclisas-status", line 103, in returnArrayInfo
    if ldpdcount and (int(spandepth) > 1):
UnboundLocalError: local variable 'ldpdcount' referenced before assignment


sudo megacli -LDInfo -Lall -a0

Adapter 0 -- Virtual Drive Information:
Virtual Drive: 1 (Target Id: 1)
Name                :home
RAID Level          : Primary-5, Secondary-0, RAID Level Qualifier-3
Size                : 1.813 TB
Sector Size         : 512
Is VD emulated      : Yes
Parity Size         : 371.597 GB
State               : Optimal
Strip Size          : 64 KB
Number Of Drives    : 6
Span Depth          : 1
Default Cache Policy: WriteThrough, ReadAheadNone, Direct, No Write Cache if Bad BBU
Current Cache Policy: WriteThrough, ReadAheadNone, Direct, No Write Cache if Bad BBU
Default Access Policy: Read/Write
Current Access Policy: Read/Write
Disk Cache Policy   : Disk's Default
Encryption Type     : None
PI type: No PI

Is VD Cached: No


Virtual Drive: 2 (Target Id: 2)
Name                :root
RAID Level          : Primary-1, Secondary-0, RAID Level Qualifier-0
Size                : 1.089 TB
Sector Size         : 512
Is VD emulated      : No
Mirror Data         : 1.089 TB
State               : Optimal
Strip Size          : 1.0 MB
Number Of Drives    : 2
Span Depth          : 1
Default Cache Policy: WriteBack, ReadAheadNone, Cached, No Write Cache if Bad BBU
Current Cache Policy: WriteBack, ReadAheadNone, Cached, No Write Cache if Bad BBU
Default Access Policy: Read/Write
Current Access Policy: Read/Write
Disk Cache Policy   : Disk's Default
Encryption Type     : None
PI type: No PI

Is VD Cached: No

Exit Code: 0x00
```

**Comment by ElCoyote27** [comment]
Hello,
Could you please check if my tree works fine with your config?
I'm pretty sure I had fixed that very bug a while ago..
See: https://github.com/ElCoyote27/hwraid/blob/master/wrapper-scripts/megaclisas-status
Thanks,
Vincent

**Comment by jbergler** [comment]
Yep it works in your tree.

**Comment by ElCoyote27** [comment]
Thanks.

**Comment by eLvErDe** [comment]
Hello,

I updated megaclisas-status with most of elcoyote patches and also generated update debian/ubuntu packages on the mirror.
Can you confirm if it has been fixed ?

Thanks.

**Comment by jbergler** [comment]
I believe this is working now, thanks

**Comment by dnleek** [comment]
Hello,

I do not believe it is currently fixed.

-- Controller information --
-- ID | H/W Model                             | RAM    | Temp | BBU    | Firmware     
c0    | Cisco 12G SAS Modular Raid Controller | 512MB  | 39C  | Good   | FW: 24.5.0-0020 

-- Array information --
-- ID | Type   |    Size |  Strpsz | Flags | DskCache |   Status |  OS Path | InProgress   
c0u1  | RAID-5 |   1813G |   64 KB | RA,WT |  Default |  Optimal | /dev/sda | None         
c0u2  | RAID-1 |   1089G |  1.0 MB | RA,WB |  Default |  Optimal | /dev/sdb | None         

-- Disk information --
Traceback (most recent call last):
  File "/usr/sbin/megaclisas-status", line 677, in <module>
    arraydisk = returnDiskInfo(output,controllerid)
  File "/usr/sbin/megaclisas-status", line 429, in returnDiskInfo
    if (( NestedLDTable[controllerid][int(arrayid)] == True) and (spanid != False)):
IndexError: list index out of range

The cause is that each row of NestedLDTable is appended to, but it is still accessed by arrayID. I have a PR in the works.

**Comment by eLvErDe** [comment]
OK we'll check this tomorrow if you're available!

Le 10 février 2016 21:58:01 GMT+01:00, dnleek <notifications@github.com> a écrit :
>Hello,
>
>I do not believe it is currently fixed.
>
>-- Controller information --
>-- ID | H/W Model                             | RAM    | Temp | BBU   
>| Firmware     
>c0    | Cisco 12G SAS Modular Raid Controller | 512MB  | 39C  | Good  
>| FW: 24.5.0-0020 
>
>-- Array information --
>-- ID | Type   |    Size |  Strpsz | Flags | DskCache |   Status |  OS
>Path | InProgress   
>c0u1  | RAID-5 |   1813G |   64 KB | RA,WT |  Default |  Optimal |
>/dev/sda | None         
>c0u2  | RAID-1 |   1089G |  1.0 MB | RA,WB |  Default |  Optimal |
>/dev/sdb | None         
>
>-- Disk information --
>Traceback (most recent call last):
>  File "/usr/sbin/megaclisas-status", line 677, in <module>
>    arraydisk = returnDiskInfo(output,controllerid)
>  File "/usr/sbin/megaclisas-status", line 429, in returnDiskInfo
>if (( NestedLDTable[controllerid][int(arrayid)] == True) and (spanid !=
>False)):
>IndexError: list index out of range
>
>The cause is that each row of NestedLDTable is appended to, but it is
>still accessed by arrayID. I have a PR in the works.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/eLvErDe/hwraid/issues/26#issuecomment-182579653

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by ElCoyote27** [comment]
I integrated dnleek's code and had a few other fixes for unconf'ed/JBOD drives..
Could you please test my current version as well?
https://raw.githubusercontent.com/ElCoyote27/hwraid/master/wrapper-scripts/megaclisas-status
Thanks,
Vincent

**Comment by eLvErDe** [comment]
Yep, in around one hour and half!

Adam

On February 11, 2016 2:50:33 AM GMT+01:00, "Vincent S. Cojot" <notifications@github.com> wrote:
>I integrated dnleek's code and had a few other fixes for unconf'ed/JBOD
>drives..
>Could you please test my current version as well?
>https://raw.githubusercontent.com/ElCoyote27/hwraid/master/wrapper-scripts/megaclisas-status
>Thanks,
>Vincent
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/eLvErDe/hwraid/issues/26#issuecomment-182670479

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by eLvErDe** [comment]
Hello,

Works correctly on two different setup so I guess it's fine. Can you do some QA on your side and then PR ?

Thx, Adam.

**Comment by ElCoyote27** [comment]
So it works fine on your JBOD disks too?
QA on my side is fine too and I merged one more patch from Dirk about HotSpare drives..
Let me PR that for you..
Thx, Vincent

**Comment by xrat** [comment]
I don't have JBOD, just wanted to report that @ElCoyote27 's version works for me. It returns
```
-- Controller information --
-- ID | H/W Model                    | RAM    | Temp | BBU    | Firmware
c0    | RAID Ctrl SAS 6G 0/1 (D2607) | 0MB    | N/A  | Absent | FW: 20.13.1-0208

-- Array information --
-- ID | Type   |    Size |  Strpsz | Flags | DskCache |   Status |  OS Path | InProgress
c0u1  | RAID-1 |    465G |   64 KB | RA,WT |  Enabled |  Optimal | /dev/sda | None
c0u2  | RAID-1 |    223G |   64 KB | RA,WT |  Enabled |  Optimal | /dev/sdb | None

-- Disk information --
-- ID  | Type | Drive Model                                     | Size     | Status          | Speed    | Temp | Slot ID  | LSI Device ID
c0u1p0 | HDD  | 9XF2J6CSST9500620NS FTA7                        | 465. Gb  | Online, Spun Up | 6.0Gb/s  | 28C  | [64:2]   | 3
c0u1p1 | HDD  | 9XF2J6BVST9500620NS FTA7                        | 465. Gb  | Online, Spun Up | 6.0Gb/s  | 28C  | [64:3]   | 0
c0u2p0 | SSD  | BTJR411205XF240AGN INTEL SSDSC2BP240G4 L2010410 | 223.0 Gb | Online, Spun Up | 6.0Gb/s  | N/A  | [64:1]   | 2
c0u2p1 | SSD  | A22K3061519001006 OCZ-VECTOR180 1.01            | 223.0 Gb | Online, Spun Up | 6.0Gb/s  | N/A  | [64:0]   | 1
```
Thanks a lot for the fix!
