### ISSUE TITLE
megaraidsas-status and unconfigured disk

### ISSUE THREAD

**Issue by Vish22** [eLvErDe/hwraid#29]
Hi,
When a disk was not configured in a array/LD (but used in JBOD mode (it's now possible with the H730P)) its flag was 'ready', but megaraidsas-status only check online et hotspare states.

Could you, please, consider the 'ready' state like you did for megaclisas-status?
(by adding at line 100 of megaraidsas-status a third test of the return keyword 'ready')

Regards.

**Comment by eLvErDe** [comment]
Hey,

Can you show me the output please ?

Thanks

**Comment by Vish22** [comment]
Here is:

sudo megaraidsas-status 
-- Arrays informations --
-- ID | Type | Size | Status

-- Disks informations
-- ID | Model | Status | Warnings
a0e32s12 | SEAGATE ST300MP0005 | ready
a0e32s13 | SEAGATE ST300MP0005 | ready


Also another server with an hybrid configuration:
-- Arrays informations --
-- ID | Type | Size | Status
a0d0 | RAID 0 | 278GiB | optimal
a0d1 | RAID 0 | 278GiB | optimal
a0d2 | RAID 0 | 3725GiB | optimal
a0d3 | RAID 0 | 3725GiB | optimal
a0d4 | RAID 0 | 3725GiB | optimal
a0d5 | RAID 0 | 3725GiB | optimal
a0d6 | RAID 0 | 3725GiB | optimal
a0d7 | RAID 0 | 3725GiB | optimal
a0d8 | RAID 0 | 3725GiB | optimal
a0d9 | RAID 0 | 3725GiB | optimal
a0d10 | RAID 0 | 3725GiB | optimal
a0d11 | RAID 0 | 3725GiB | optimal

-- Disks informations
-- ID | Model | Status | Warnings
a0e32s0 | WD WD4001FYYG 3726GiB | online
a0e32s1 | WD WD4001FYYG | ready
a0e32s2 | WD WD4001FYYG | ready
a0e32s3 | WD WD4001FYYG 3726GiB | online
a0e32s4 | WD WD4001FYYG 3726GiB | online
a0e32s5 | WD WD4001FYYG 3726GiB | online
a0e32s6 | WD WD4001FYYG 3726GiB | online
a0e32s7 | WD WD4001FYYG 3726GiB | online
a0e32s8 | WD WD4001FYYG 3726GiB | online
a0e32s9 | WD WD4001FYYG 3726GiB | online
a0e32s10 | WD WD4001FYYG 3726GiB | online
a0e32s11 | WD WD4001FYYG 3726GiB | online
a0e32s12 | SEAGATE ST9300653SS 279GiB | online
a0e32s13 | SEAGATE ST9300653SS 279GiB | online


REgards.

**Comment by eLvErDe** [comment]
Can you grab megaraidsas-status from the git repo (I just committed something) and confirm it fixes your issue.
If so, i'll release an update.

**Comment by Vish22** [comment]
Works like a charm!

Thx.

**Comment by ElCoyote27** [comment]
Hi Vish22, could you please test this other version:
https://raw.githubusercontent.com/ElCoyote27/hwraid/master/wrapper-scripts/megaclisas-status
I believe I fixed the regression I had induced and it should now display unconf and JBOD drives corretly.. 
Sorry about that.
Vincent

**Comment by eLvErDe** [comment]
Hello,

I just released megaraid-status program version 0.12. Could you please upgrade your package and confirm everything is ok now ? That could help to close this ticket :-)

Regards, Adam.
