### ISSUE TITLE
Please upgrade megacli to newer upstream version

### ISSUE THREAD

**Issue by its-not-a-bug-its-a-feature** [eLvErDe/hwraid#3]
Hello,

I find that the current version of megacli does not report FANs that are present and working on a LSI SAS expander, behind a LSI 9266-8i card.

root@host:~# dpkg -l | grep megacli
ii  megacli                            8.04.07-1                     amd64        LSI Logic MegaRAID SAS MegaCLI

root@host:~# /usr/sbin/megacli -EncInfo -aALL | grep Fan\ Status
Fan Status                   : Not Installed
Fan Status                   : Not Installed
Fan Status                   : Not Installed
Fan Status                   : Unknown
Fan Status                   : Unknown
Fan Status                   : Unknown
Fan Status                   : Unknown
Fan Status                   : Unknown

With the newer 8.07.07 version of MegaCLI I see correct info:

root@host:~# MegaCLI-8.07.07/MegaCli64 -EncInfo -aALL | grep Fan\ Status
Fan Status                   : Not Installed
Fan Status                   : Not Installed
Fan Status                   : Not Installed
Fan Status                   : OK
Fan Status                   : OK
Fan Status                   : OK
Fan Status                   : Unknown
Fan Status                   : Unknown

The version above came from http://www.lsi.com/downloads/Public/MegaRAID%20Common%20Files/8.07.07_MegaCLI.zip but I think there may be a newer release as well.

**Comment by eLvErDe** [comment]
Hello,

Megacli package is currently at 8.07.14 relase :-)

Regards, Adam.
