### ISSUE TITLE
megaclisas-status and Hotspare

### ISSUE THREAD

**Issue by Tuxdiver** [eLvErDe/hwraid#31]
Hi,

we have an unconfigured hotspare drive and megaclisas-status reports the RAID as not optimal.

This patch fixes it for me:

```
diff --git a/wrapper-scripts/megaclisas-status b/wrapper-scripts/megaclisas-status
index c212e03..891f6ba 100755
--- a/wrapper-scripts/megaclisas-status
+++ b/wrapper-scripts/megaclisas-status
@@ -756,7 +756,7 @@ if totalunconfdrivenumber:
                arraydisk = returnUnconfDiskInfo(output,controllerid)
                for array in arraydisk:
                        dbgprint('Disk c'+str(controllerid)+'uXpY status : ' + array[3])
-                       if array[3] not in [ 'Online', 'Unconfigured(good), Spun Up', 'JBOD' ]:
+                       if array[3] not in [ 'Online', 'Unconfigured(good), Spun Up', 'JBOD','Hotspare, Spun Up' ]:
                                bad = True
                                nagiosbaddisk=nagiosbaddisk+1
                        else:

```

Not sure, if it could be 'Hotspare' only...

Best regards,

Dirk

**Comment by ElCoyote27** [comment]
Hi Dirk,
Thanks for the patch. I've merged your patch into my repo. I'm going to issue a new PR for the main repo. Please test again when it's released.
Thanks,
Vincent

**Comment by gfab23** [comment]
Hello
I have the same situation, but in my case the hotspare was in spun down state shown as: '`Hotspare, Spun down`'.
Eventually also adding this to the check could probably be helpful for others. In my case I changed the hotspare to be in spin up state with this (for adapter 0):
`megacli -AdpSetProp -DsblSpinDownHSP -1 -a0`
I think it is more useful to have the hotspare also in use (spinning) and be able so see when it fails, as it may not spin up when it would be needed for recovery.

bye
Fabian

**Comment by eLvErDe** [comment]
Hey,

I merged the big pull request from elcoyote including this one.
Also, I'll have Hotspare, Spun Down to the whitelist.

Regards, Adam.

**Comment by ElCoyote27** [comment]
Hey,
Thanks for the merge.
Just a thought: Are we sure if we should consider 'Hotspare, Spun Down' to be OK?
Thanks,
Vincent

**Comment by eLvErDe** [comment]
Hello,

 

Well it seems to be some kind of power saving feature. A friend also have the same behaviour on its RAID and the drive is definitely not broken, so yes, I guess…

 

Adam.
