### ISSUE TITLE
megaclisas-status, Debian and cron

### ISSUE THREAD

**Issue by asheetz2000** [eLvErDe/hwraid#35]
When run from cron (and how else would one run it?) megaclisas-status returns

```
# This script requires Administrator privs! e.g :
sudo /usr/sbin/megaclisas-status
```

Line 42 should read
`if os.getenv('LOGNAME') != 'root':`
instead of
`if os.getenv('USER') != 'root':`

**Comment by fluxcorenz** [comment]
Agreed, also seeing this problem.

**Comment by eLvErDe** [comment]
Hello,

It's not working that way anymore... Can you confirm current version works as expected ?

Thanks, Adam.
