### ISSUE TITLE
megaclisas-statusd emails too often

### ISSUE THREAD

**Issue by dnleek** [eLvErDe/hwraid#40]
megaclisas-statusd checks every 10 minutes for a state change, but should only email every 2 hours for a status change. One of our disks failed, so we should be getting emailed every 2 hours now. However, because the temperature of the disks are constantly changing by one or two degrees, the text result of megaclisas-status changes slightly every 10 minutes, so megaclisas-statusd emails every time.

**Comment by csjn** [comment]
+1
I am just having this issue and was digging thru the code. The current code nearly makes the var 'REMIND' useless :-\

My (poor) programming knowledge tells me, that the wrapper-script 'megaclisas-status' needs to be altered, e.g. a parameter to surpress the temperature column.

**Comment by eLvErDe** [comment]
Your poor programming skills are just fine, that's indeed the easiest workaround.

On top of my to-do list...

**Comment by ElCoyote27** [comment]
@eLvErDe I can probably write a quick patch to megaclisas-status to offer an argument that won't show the temperature (we still want to show it by default, right?).
How would that sound?

**Comment by csjn** [comment]
@ElCoyote27 that would be great. The init-script needs to use that argument.

**Comment by ElCoyote27** [comment]
Hi,
Fixed in my tree (pull request #47 ).
Added '--notemp' to megaclisas-status and made the Debian init script call megaclisas-status with this extra argument.
Please pull,
Thank you,
Vincent

**Comment by eLvErDe** [comment]
Go ahead... I'll update the debian packaging to pass this new argument.

Adam

On October 20, 2016 7:01:24 PM GMT+02:00, "Vincent S. Cojot" <notifications@github.com> wrote:
>@eLvErDe I can probably write a quick patch to megaclisas-status to
>offer an argument that won't show the temperature (we still want to
>show it by default, right?).
>How would that sound?
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/eLvErDe/hwraid/issues/40#issuecomment-255165728

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by ElCoyote27** [comment]
Hi Adam,
It's already fixed in the latest Pull Request. I modified the debian packaging as well.
Regards,
Vincent

**Comment by eLvErDe** [comment]
Hello,

I rebased it and merged. I'm currently building updated Debian packages for the repository.
Btw, I know you're interested in Python so you may consider having a look at aacraid-status wrapped, I updated it with a real argument parser module.

Thanks,

Adam.
