### ISSUE TITLE
Change SHA1 to SHA256 for repository signing (Release.gpg)

### ISSUE THREAD

**Issue by svamberg** [eLvErDe/hwraid#43]
Hello,
please change repository signing from SHA1 to SHA256. I get message:
`..../Release.gpg: Signature by key 0073C11919A641464163F7116005210E23B3D3B4 uses weak digest algorithm (SHA1)` when using `apt-get update` on Debian Stretch or Sid (I have apt 1.2.10 version).

I solve this warning by [changing preferences of keys](https://www.debian-administration.org/users/dkg/weblog/48)  and adding `--digest-algo SHA256` to `gpg` command on my repository.

Thanks

**Comment by bootc** [comment]
I'd like to second this. Debian sid and stretch now warn about this condition and the aim is to remove SHA-1 signature support as soon as is feasible. This causes warnings such as:

```
W: http://hwraid.le-vert.net/debian/dists/sid/Release.gpg: Signature by key 0073C11919A641464163F7116005210E23B3D3B4 uses weak digest algorithm (SHA1)
```

**Comment by paulinsche** [comment]
I'd like to second this. Xenial Xerus has the same warnings:

`W: http://hwraid.le-vert.net/ubuntu/dists/trusty/Release.gpg: Signature by key 0073C11919A641464163F7116005210E23B3D3B4 uses weak digest algorithm (SHA1)`

**Comment by jeff-dagenais** [comment]
Hi all,

Although I completely respect the case about now weak sha1, may I point out that when we setup the hwraid repo using the `wget -O - http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key | sudo apt-key add -` instruction, said key is obtained without any trust! (or did I miss something?)

Some order of trust could be gained by simply having the key served over https or having the key itself signed by peers and/or upstream authorities. I'm no expert, but his may help: https://wiki.debian.org/Keysigning#Step_6:_Get_your_key_digitally_signed

Merci Adam pour ce projet magnifique! ;)

**Comment by bootc** [comment]
@jeff-dagenais: I think most of us are commenting on this because newer APT complains loudly about the repository not being secure and not wanting to see these warnings any more. This should be a straightforward fix, particularly as the repository is already signed.

I completely agree that having a better method of obtaining the key would be preferential, as would having it signed by some real persons, but that's beyond the scope of this ticket.

**Comment by jeff-dagenais** [comment]
Agreed. It is off topic for this ticket. I apologize. I didn't intend to hijack the thread, but merely poke at another security related issue while I had the attention of concerned contributors. Probing to see if a proper issue about this should be created.

**Comment by eLvErDe** [comment]
Hey guys,

I'll try to fix this asap and will provide the key using letsencrypt https.

Adam

**Comment by eLvErDe** [comment]
Guys,

Release.gpg is now signed using SHA256 instead of SHA1 and I fixed letsencrypt SSL certificate for hwraid.le-vert.net virtual host. My sid APT doesn't complain anymore and I fixed the wiki page to download using HTTPS.

Is that enough ?

Regards, Adam.

**Comment by jeff-dagenais** [comment]
Hi Adam,

Thanks for https! ;) Tried it though, on debian jessie...

Cleared the old keys using `apt-key del 9887F95A`. Confirmed `apt-get update` would now give me the warning. Then added the new key using the new https address in command found on your website. Confirmed the key added:
```
# apt-key list |grep --context=3 hwraid
sub   2048g/3CAF4617 2010-03-30

pub   2048R/23B3D3B4 2013-07-24
uid                  HWRaid (http://hwraid.le-vert.net) <root@hwraid.le-vert.net>
sub   2048R/34A9CF8E 2013-07-24

/etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg
```
now `apt-get update` gives:
```
W: GPG error: http://download.proxmox.com jessie Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C23AC7F49887F95A
```

**Comment by eLvErDe** [comment]
Proxmox ;)

Btw; no need to purge the key from GPG, it's still the same except that I force SHA256 cypher when generating Release.gpg

**Comment by jeff-dagenais** [comment]
Crap! Sorry! My desire to help overcame my thoroughness here. Then all is well, I approve this fix! ;)

**Comment by bootc** [comment]
@eLvErDe Thank you very much! Yes, I can confirm Apt in Stretch no longer complains about your repo. As far as I'm concerned this should be good to close. @svamberg ?

**Comment by paulinsche** [comment]
Everything fine here. Thank you!

**Comment by eLvErDe** [comment]
Let's consider this as fixed, feel free to reopen
