### ISSUE TITLE
naming off debs

### ISSUE THREAD

**Issue by geosone** [eLvErDe/hwraid#44]
if 2 debs from diffent repos have the same filename but differnt fiel size its really hard to mirror your repo to a lokal repo.

could you ranme the packages or add the distro name to the package name

**Comment by eLvErDe** [comment]
Hello,

Indeed some tools don't like this but right now I don't know how to do better. I'm building all packages using various cowbuilders; do you know if there's a way to build a package in cowbuilder/pbuilder and automatically append a tag to the package version ?

Adam

**Comment by geosone** [comment]
yes teh source package must already have the changed verison number but then building is hell so i am at the moment implementing jenkins-debian-glue (not only for debian also for ubuntu) for the hpacucli tool based on your package so just wait.

**Comment by geosone** [comment]
http://dev.disconnected-by-peer.at:8080/ you can see the hpacucli package build for jessie weezy i386 amd64 i have also created an bash script to download the aktuall rpm and creating the source package for git persisten upload http://git.disconnected-by-peer.at/hwraid/hpacucli/

**Comment by eLvErDe** [comment]
Hello,

I fixed all package to override dh_gencontrol to add a distribution tag based on lsb-release.

Regards
