### ISSUE TITLE
Provide Xenial packages

### ISSUE THREAD

**Issue by vincentbernat** [eLvErDe/hwraid#58]
Hey!

Would it be possible to provide Xenial packages? Jessie packages should work fine but people looking at Xenial packages can't know that.

**Comment by g1franc** [comment]
+1

**Comment by N11N** [comment]
+1

**Comment by eLvErDe** [comment]
Hello,

It's available. Can you confirm and close ?

Thanks,

Adam.

**Comment by vincentbernat** [comment]
Thanks! Works for me.
