### ISSUE TITLE
Awkward copy/paste bug on the wiki

### ISSUE THREAD

**Issue by qoole** [eLvErDe/hwraid#60]
Hiya,

First off - thanks for an AWESOME repo!

Could you add code tags to the https://hwraid.le-vert.net/wiki/DebianPackages page around the sources.list examples at the top because that little icon between the deb and http throws off copy & pastes of the URL

![image](https://cloud.githubusercontent.com/assets/2862661/24197391/5a7d9466-0ef9-11e7-97e5-82a86ab3048f.png)

copying the above link results in the following bytes appearing in the text when pasted (the first deb line is manually typed. The second, with highlighted extra bytes, is copy and pasted from wiki page)

![image](https://cloud.githubusercontent.com/assets/2862661/24197413/6c6f6366-0ef9-11e7-9778-4bc944cd79c5.png)

Thanks,

Alex

**Comment by eLvErDe** [comment]
Hello,

I type the whole line again and did a copy/paste to my sources.list and it worked.
Thanks for reporting.
