### ISSUE TITLE
Segfaulting on CentOS 7

### ISSUE THREAD

**Issue by Bernd2** [eLvErDe/hwraid#66]
Hi,

I see this trying to fire up arcconf on CentOS 7:

# /usr/Arcconf/arcconf 
Segmentation fault

# ldd /usr/Arcconf/arcconf
	linux-vdso.so.1 =>  (0x00007ffe6fa6f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f8c260f2000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8c25ed6000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f8c25bcc000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f8c258ca000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8c256b4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f8c252f2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8c262ff000)

CentOS Linux release 7.3.1611 (Core) 

Linux blabla 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eLvErDe** [comment]
Hi,

I'm not the owner of Adaptec stuff at all, just distributing wrappers around their tools. Please contact Adaptec.

Regards, Adam.

**Comment by wefixit-AT** [comment]
@Timo3924 Hi, today I came to the same problem. Did you get a response from Adaptec or found any solution?
