### ISSUE TITLE
Ubuntu Trusty builds needed

### ISSUE THREAD

**Issue by robbat2** [eLvErDe/hwraid#7]
Please put up Ubuntu builds for trusty. Should be a simple 1:1  of precise for now?

**Comment by eLvErDe** [comment]
Hello,

Trusty repository has been added. Can you confirm and close the ticket if it's ok ?

Thanks, Adam.

**Comment by ssaki** [comment]
@eLvErDe, hpacucli seems to be OK on fresh 14.03, thanks!
