### ISSUE TITLE
CRITICAL: packages changed without updating the version

### ISSUE THREAD

**Issue by sandrotosi** [eLvErDe/hwraid#74]
Hello,
it appears you have rebuilt/changed the packages in your repo without updating their versions; for example, i now have:

```
32899957 5360 -rw-r--r--   2 root     root      5486420 Jul  6  2015 pool/ce/61/3dm2_2.11.00.019+10.2.1+KB16625-1_amd64.deb
32113554 4852 -rw-r--r--   1 root     root      4964368 Oct  3 17:29 pool/b9/0a/3dm2_2.11.00.019+10.2.1+KB16625-1_amd64.deb

```

so same file, same exact version but different sizes (first line is from the wheezy repo, the second one if from the stretch one)

what's going on here?

**Comment by eLvErDe** [comment]
Hi,

Nothing weird here, they have been built in different environment (wheezy, stretch) so Debian helpers generated something slithly different.

**Comment by sandrotosi** [comment]
yeah but you expose the same package to the package manager while it's actually different! never ever replace the triplet <pkgname, arch, version> with something that's not bit-by-bit equivalent :(

**Comment by eLvErDe** [comment]
Well that works for Debian, but hardly for 3rd parties package, same source built for several targets.

When I'm doing that now I override dh_gencontrol to append distribution tags using lsb_release. But that's a HUGE work to fix all hwraid packages :(

**Comment by sandrotosi** [comment]
there are several examples of third-party repositories with tools rebuilt for several distributions using a suffix to specifically differentiate this case: use for example +debN with N=8 for jessie and 9 for stretch.

i DO appreciate your work here, but this is causing real issue to your users - while i understand it may be a lot of work (but i suspect most of if can be automated away) to fix the current repo, keep it in mind for the future releases

**Comment by eLvErDe** [comment]
I can't be automated. Metadata are inside the deb file, so either you do shitty stuff extracing .deb content and patching metadata inside or you do this at build time by injecting tags when generating control files...

**Comment by eLvErDe** [comment]
What problem do you have ? Reprepo ?

**Comment by sandrotosi** [comment]
aptly

```ERROR: unable to publish: unable to process packages: error linking file to /var/cache/aptly/public/hwraid/pool/main/3/3dm2/3dm2_2.11.00.019+10.2.1+KB16625-1_amd64.deb: file already exists and is different```

**Comment by sathieu** [comment]
The common way to fix this is to suffix the version with the release number. i.e:
- `megacli 8.07.14-1~deb7`
- `megacli 8.07.14-1~deb8`
- `megacli 8.07.14-1~deb9`

And if there are packaging changes without source change:
- `megacli 8.07.14-1~deb7u1`
- `megacli 8.07.14-1~deb8u1`
- `megacli 8.07.14-1~deb9u1`

**Comment by eLvErDe** [comment]
Hello, I am aware about this but there's no way I create a different source package for each distro.
For other projects I use lsb-release to generate a distrib tag and use it to override dh_gencontrol call. If you have a better idea, I'm listening !

**Comment by sathieu** [comment]
And using `dch -v <version>` before building?

**Comment by eLvErDe** [comment]
Hello,

All packages have been modified to add distribution tag based on lsb-release and rebuilt.
You should be fine using reprepo now !
