### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by tbals** [eLvErDe/hwraid#76]
I am using Ubuntu 16.04.2 LTS:

# wget -O - https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key | sudo apt-key add -
--2017-11-06 13:38:01--  https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key
Resolving hwraid.le-vert.net (hwraid.le-vert.net)... 163.172.69.161, 2001:bc8:357c::1
Connecting to hwraid.le-vert.net (hwraid.le-vert.net)|163.172.69.161|:443... connected.
ERROR: cannot verify hwraid.le-vert.net's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to hwraid.le-vert.net insecurely, use `--no-check-certificate'.
gpg: no valid OpenPGP data found.

**Comment by dubcl** [comment]
Hi, same here, Debian Jessie

```
$  wget -O - https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key | apt-key add -     
--2017-11-06 12:11:47--  https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key
Resolving hwraid.le-vert.net (hwraid.le-vert.net)... 163.172.69.161, 2001:bc8:357c::1
Connecting to hwraid.le-vert.net (hwraid.le-vert.net)|163.172.69.161|:443... connected.
ERROR: The certificate of ‘hwraid.le-vert.net’ is not trusted.
ERROR: The certificate of ‘hwraid.le-vert.net’ has expired.
The certificate has expired
gpg: no valid OpenPGP data found.
```

**Comment by eLvErDe** [comment]
Hi there,

Just had to reload nginx, not sure why I used to leave it up to certbot and it used to work just fine....

Regards, Adam.
