### ISSUE TITLE
megaclisas-status (RAID60-checks)

### ISSUE THREAD

**Issue by kasimovv** [eLvErDe/hwraid#85]
Hello, Elverde.
Could you help me, please.
Your script is very useful, but i have some issues.
I use this script with storcli, on ESXi host, with raid60, and i have this result:
![image](https://user-images.githubusercontent.com/20535897/36603473-e6cbb5f6-18cb-11e8-894b-6bb7cd174253.png)

I changed path to my storcli file, and script works fine, but i have this result with unconfigured drives and info with NOT OPTIMAL state. And i also checked this script on the server with raid10, and storcli, and it works fine, without unconfigured disk information:
![image](https://user-images.githubusercontent.com/20535897/36603429-c59c6920-18cb-11e8-9de2-74857361c9ca.png)

Please, help me.

**Comment by ElCoyote27** [comment]
Hi,
Could you please try the latest megaclisas-status version from here:
https://raw.githubusercontent.com/ElCoyote27/hwraid/master/wrapper-scripts/megaclisas-status

If the output still shows some error, could you please run the script with '--debug' and attach the output here.

Thank you,
Vincent

**Comment by kasimovv** [comment]
Hello. Thank you for helping.
I tried new version, but i got the same error (
Here is --debug:
[megaclisas-status --debug.txt](https://github.com/eLvErDe/hwraid/files/1755938/megaclisas-status.--debug.txt)
And here is the script with my changes ( i just changed path):
[megaclisas-status.zip](https://github.com/eLvErDe/hwraid/files/1755942/megaclisas-status.zip)

Please look attached files.

**Comment by kasimovv** [comment]
@ElCoyote27
Hello, Vincent. Thank you for helping.
I tried new version, but i got the same error (
Here is --debug:
[megaclisas-status --debug.txt](https://github.com/eLvErDe/hwraid/files/1755938/megaclisas-status.--debug.txt)
And here is the script with my changes ( i just changed path):
[megaclisas-status.zip](https://github.com/eLvErDe/hwraid/files/1755942/megaclisas-status.zip)

Please look at the attached files

**Comment by ElCoyote27** [comment]
Hi Kasimovv,
That's interesting. I didn't know storcli supported the same syntax as megacli.. where did you get storcli from? Do you happen to have an URL and/or version?
Still investigating,
Vincent

**Comment by ElCoyote27** [comment]
Could you please provide me with the output of:
storcli -PDList -a0 -NoLog
Thank you,
Vincent

**Comment by kasimovv** [comment]
@ElCoyote27 
Hi, Vincent. 
Here we go: https://docs.broadcom.com/docs/1.23.02_StorCLI (the latest version)
And the output of the command (storcli -PDList -a0 -NoLog) : 
[output.txt](https://github.com/eLvErDe/hwraid/files/1759284/output.txt)

Please look at the attached files.

**Comment by ElCoyote27** [comment]
Hi Kasmiovv,
Please try this new build: https://github.com/ElCoyote27/hwraid/blob/master/wrapper-scripts/megaclisas-status
As usual, please run it with '--debug' and please send me the output if it still doesn't work properly.
Also, please note that you shouldn't have to modify the paths inside the script as I've added storcli.
Regards,
Vincent

**Comment by ElCoyote27** [comment]
Hi Kasimovv,
Nope, it does not look -that- good as it is still missing out on the hotspares that you have. Couls you please send me the PDinfo output I requested earlier?
I will take a look when I reach the office (I am in Canada).
Regards,
Thanks,

**Comment by kasimovv** [comment]
@ElCoyote27 
Hi, Vincent. Hello from Russia :)
Thank you, attached output.
[output_PDinfo.txt](https://github.com/eLvErDe/hwraid/files/1763216/output_PDinfo.txt)

**Comment by ElCoyote27** [comment]
Hi Kasimovv,
I see part of the reason why you are experiencing a problem: Someone at LSI typoed the output messages when they ported some of the stuff from MegaCLI.
Check the differences below:
Storcli:
```
$ strings -a output_PDinfo.txt|grep -i drive.*pos.*tion|head -2
Drive's postion: DiskGroup: 0, Span: 0, Arm: 0
Drive's postion: DiskGroup: 0, Span: 0, Arm: 1
```
MegaCli:
```
[root@vkvm1 ~]# /opt/MegaRAID/MegaCli/MegaCli64 -PDList -a0 -NoLog|grep -i drive.*pos.*tion|head -2
Drive's position: DiskGroup: 0, Span: 0, Arm: 0
Drive's position: DiskGroup: 0, Span: 0, Arm: 1
```
In 'Storcli', Megacli's 'POSITION' became 'POSTION' (note the missing 'I')
Fortunately, in Python it is very easy to deal with such an issue thanks to the regexp's there..
Let me fix that and get back to you.
Regards,

**Comment by ElCoyote27** [comment]
Hi Kasimovv,
Please try out the new version at: https://github.com/ElCoyote27/hwraid/blob/master/wrapper-scripts/megaclisas-status
Please run it with --debug too and attach the output here.
Thank you very much,
Vincent

**Comment by kasimovv** [comment]
Hello, Vincent.
Thank you very much.
I tried your new version, but output was the same, take a look:
![image](https://user-images.githubusercontent.com/20535897/36782323-a80b60ca-1c89-11e8-80e9-33c8d34f9b66.png)
Here it is (--debug):
[output.txt](https://github.com/eLvErDe/hwraid/files/1766609/output.txt)

**Comment by ElCoyote27** [comment]
Hi Kasimovv,
Here it goes again:
Please try out the new version at: https://github.com/ElCoyote27/hwraid/blob/master/wrapper-scripts/megaclisas-status
Please run it with --debug too and attach the output here.
Thank you very much,
Vincent

**Comment by kasimovv** [comment]
@ElCoyote27 
Hi, Vincent.
Yeees, new version is showing Hot Spare drives:
![image](https://user-images.githubusercontent.com/20535897/36833862-ddebe56c-1d41-11e8-930f-8522935734b6.png)
--debug: 
[output.txt](https://github.com/eLvErDe/hwraid/files/1770319/output.txt)
Thank you very much, for this very useful script, and your help. Have a nice day.

**Comment by ElCoyote27** [comment]
Hi kasimovv,
Thank you very much for your help. Thanks to your report, I was able to add support for PERcli and Storcli, fix a few buys and improve debugging output. Thanks for your contributions.
Regards,
Vincent

**Comment by kasimovv** [comment]
@ElCoyote27 Hello, Vincent.
Could you help me please. Is this possible , to use this script like Nagios plugin with Nagios ? Have a nice day.

Best regards, Vil Kasimov.

**Comment by ElCoyote27** [comment]
@kasimovv the way this script is used through nagios is to pass the --nagios arg to it, e.g:
# megaclisas-status --nagios
RAID OK - Arrays: OK:2 Bad:0 - Disks: OK:2 Bad:0
Is that what you are looking for?
Vincent

**Comment by kasimovv** [comment]
Hello, Vincent.
Forgive me for the long answer, I was on a sick leave. 
I mean , is it possible to use it, like (on remote host):
![image](https://user-images.githubusercontent.com/20535897/37825618-8cc0e8d8-2ea1-11e8-8196-51e7c6cea1ed.png)
If this were possible, this would greatly simplify the verification of the array.

Have a nice day.
Best regards
Vil Kasimov

**Comment by kasimovv** [comment]
Hi, Vincent.
I was able to implement the ESXi check via Nagios and the check_by_ssh plugin, I did not know about that check at all. :) Example below:
![image](https://user-images.githubusercontent.com/20535897/38032274-e849fc78-32a5-11e8-838a-39e7e2dd9d38.png)

Have a nice day.
Best regards
Vil Kasimov
