### ISSUE TITLE
Dell PERC H310

### ISSUE THREAD

**Issue by PoviViki** [eLvErDe/hwraid#93]
Hello

I would like to ask for some help. I want to build a media server, with fresh install desktop Ubuntu (18.04.1) and KODI, but the operating system does not see the raid card (Dell PERC H310)
I installed the "megaraid sas-status" program, which says: No MEGAraid or PERC adapter detected on your system.
At windows I would say: no driver is installed. But I'm still starting in linux.
Can anyone help me with this?

Thanks
PoviViki

**Comment by eLvErDe** [comment]
Hello,

This is not the proper package for this card. Please install `megaclisas-status`

Adam.
