### ISSUE TITLE
Repository for Debian buster

### ISSUE THREAD

**Issue by gedia** [eLvErDe/hwraid#98]
Hello,

Any plans to publish a repo for debian "buster" now that it's in Hard Freeze? Or should we be expecting it after its release? Thanks!

**Comment by eLvErDe** [comment]
Hello,

Yes it's on my TODO list, it'll be done before release.

**Comment by sim0nx** [comment]
Hi,

Buster will be out on 6th of july ... do you need any help ? :-)

**Comment by eLvErDe** [comment]
It'll be ready, probably start working on it tomorrow

**Comment by eLvErDe** [comment]
Ready !

**Comment by sim0nx** [comment]
woohoo, thank you !

**Comment by gedia** [comment]
Thanks!
